### ISSUE TITLE
Config is not Sync

### ISSUE THREAD

**Issue by rw** [mdboom/jsonschema-valid#10]
It would be convenient to be able to use a Config from multiple threads (using, say, an Arc).

**Comment by badboy** [comment]
What would be the use case?
What stops you from implementing that in your own code right now?

(I do agree in that I think the config should own the schema `Value` instead of just a reference to it)

**Comment by rw** [comment]
I think the problem is actually the dyn Trait. My use case is creating a schema at program start (using lazy_static or similar), then using it from async tasks.

**Comment by badboy** [comment]
Hm, true, that might be another problem. Unfortunately making it a generic instead of a `dyn Trait` requires a lot of generic annotations right now :/

**Comment by rw** [comment]
@badboy Maybe use an enum to wrap the possible draft implementations? Then, instead of a dyn Trait, use that enum on the Config object.

**Comment by badboy** [comment]
I thought about that too. Regardless of which way we go it's going to cause some changes across the board because of the current layout.

I'm not saying we shouldn't do that, it's just a bit of tedious work (and not super high priority)

**Comment by rw** [comment]
@badboy If there's another way to do what I need, could you show me? Right now, it seems there's no combination of RwLock/Arc/Box that I can use to make this threadsafe.

**Comment by rw** [comment]
@badboy Also, IMO, a lot of people will want to use this library like I am: sharing the validator between threads (or async tasks).

**Comment by badboy** [comment]
I totally understand that use case and admit that the current API is not suitable for it.
I plan to spend a bit of time on this next week (this is a work project, so I'm not going to use my weekend for it ;))

**Comment by badboy** [comment]
I played around with using an enum instead of a trait (and dynamic trait dispatch).
You can find the code here: https://github.com/mdboom/jsonschema-valid/compare/master...badboy:less-dynamic-api
(including an example for threaded usage).

It's changing the API only slightly, but it works better for the end users I think. I will send that as a PR and discuss with mdboom if we want to switch it.

**Comment by rw** [comment]
LGTM. The dyn Trait did seem like overkill, I'm glad the enum suggestion worked out!

**Comment by badboy** [comment]
#13 landed and I'm about to do a release.
