### ISSUE TITLE
expose error fields

### ISSUE THREAD

**Issue by softprops** [mdboom/jsonschema-valid#2]
Thanks for publishing this crate. It works great!

I'd like to use it in a cli context and would find it helpful to have access to the error paths. https://github.com/mdboom/jsonschema-valid/blob/81b34c3a4aac15c1fd856fce35156e0bc9b39315/src/error.rs#L15

I could parse these out of the Display output but I'd like not to rely on the display formats stability to get access to structured information

**Comment by mdboom** [comment]
Great idea.  This library is going through a major refactor, and I'll definitely include this as part of that.

**Comment by softprops** [comment]
Thanks. That would be great. I'm currently working around this with regexes and parsing error strings :) https://github.com/softprops/splint/blob/master/src/main.rs#L85

**Comment by vasilakisfil** [comment]
@mdboom thanks for this library. I would like to also second that, we need a way to access the error messages, it wouldn't hurt to make [these](https://github.com/mdboom/jsonschema-valid/blob/master/src/error.rs#L13-L15) public I think ?

**Comment by mdboom** [comment]
Fixed by #8.
